# =================================================================== #
#                 LionAPI Configuration File                          #
# =================================================================== #
# For help: https://github.com/LionCraft08/LionAPI/                   #
# =================================================================== #

# IMPORTANT: Do not change this version number. It is used by the plugin
# to automatically update the configuration with new settings.
config-version: 1.2

settings:
  teams:
    has-backpack: true
    backpack-size: 54
    display-teamname: false
    allow-teammsg: true
  challenge-server: true

  timer:
    #What to display when the timer is paused.
    #Can be OFF (Nothing), TIMER (The current time of the timer) or MESSAGE (A Timer Paused Message)
    when-paused: OFF


#Manages connection to other servers.
server-connection:

  #Velocity connection, manages the connection to a proxy server
  velocity:
    #Type, the way to connect to a server. Can be:
    # blocked: Blocks every connection to other servers.
    # auto: Detects/Configures connections automatically, if possible
    # player: Connects via minecraft's built-in Plugin Messaging feature, requires no additional port management
    #         but won't work when no player is connected (client->velocity->backend connection required)
    # direct: Uses the own data transfer method of LionSystems. Requires a lot of setup (see below)
    #       but works without any dependency of player connections
    type: auto
    # The IP of the Proxy, required for type: direct, recommended for type: auto
    ip: 127.0.0.1
    #Never change this for the Velocity connection
    server: false
    # The Port of the Proxy, required for type: direct, recommended for type: auto
    port: 25689

  # If you need a connection to a different server, that does not depend on the velocity connection, add it here
  example-server:
    type: blocked
    ip: 176.123.234.17
    port: 69696
    server: true # Whether this machine acts as a tcp server, doesn't affect the connection, just set it different on both machines




#The Items below won't occur in the Random Item giver Methods
disabled-items:
  - BEDROCK
  - BUDDING_AMETHYST
  - BUNDLE
  - CHORUS_PLANT
  - SPAWNER
  - FARMLAND
  - INFESTED_STONE
  - INFESTED_COBBLESTONE
  - INFESTED_STONE_BRICKS
  - INFESTED_MOSSY_STONE_BRICKS
  - INFESTED_CRACKED_STONE_BRICKS
  - INFESTED_CHISELED_STONE_BRICKS
  - INFESTED_DEEPSLATE
  - REINFORCED_DEEPSLATE
  - END_PORTAL_FRAME
  - COMMAND_BLOCK
  - BARRIER
  - LIGHT
  - DIRT_PATH
  - REPEATING_COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - STRUCTURE_VOID
  - STRUCTURE_BLOCK
  - JIGSAW
  - ALLAY_SPAWN_EGG
  - AXOLOTL_SPAWN_EGG
  - BAT_SPAWN_EGG
  - BEE_SPAWN_EGG
  - BLAZE_SPAWN_EGG
  - CAT_SPAWN_EGG
  - CAMEL_SPAWN_EGG
  - CAVE_SPIDER_SPAWN_EGG
  - CHICKEN_SPAWN_EGG
  - COD_SPAWN_EGG
  - COW_SPAWN_EGG
  - CREEPER_SPAWN_EGG
  - DOLPHIN_SPAWN_EGG
  - DONKEY_SPAWN_EGG
  - DROWNED_SPAWN_EGG
  - ELDER_GUARDIAN_SPAWN_EGG
  - ENDER_DRAGON_SPAWN_EGG
  - ENDERMAN_SPAWN_EGG
  - ENDERMITE_SPAWN_EGG
  - EVOKER_SPAWN_EGG
  - FOX_SPAWN_EGG
  - FROG_SPAWN_EGG
  - GHAST_SPAWN_EGG
  - GLOW_SQUID_SPAWN_EGG
  - GOAT_SPAWN_EGG
  - GUARDIAN_SPAWN_EGG
  - HOGLIN_SPAWN_EGG
  - HORSE_SPAWN_EGG
  - HUSK_SPAWN_EGG
  - IRON_GOLEM_SPAWN_EGG
  - LLAMA_SPAWN_EGG
  - MAGMA_CUBE_SPAWN_EGG
  - MOOSHROOM_SPAWN_EGG
  - MULE_SPAWN_EGG
  - OCELOT_SPAWN_EGG
  - PANDA_SPAWN_EGG
  - PARROT_SPAWN_EGG
  - PHANTOM_SPAWN_EGG
  - PIG_SPAWN_EGG
  - PIGLIN_SPAWN_EGG
  - PIGLIN_BRUTE_SPAWN_EGG
  - PILLAGER_SPAWN_EGG
  - POLAR_BEAR_SPAWN_EGG
  - PUFFERFISH_SPAWN_EGG
  - RABBIT_SPAWN_EGG
  - RAVAGER_SPAWN_EGG
  - SALMON_SPAWN_EGG
  - SHEEP_SPAWN_EGG
  - SHULKER_SPAWN_EGG
  - SILVERFISH_SPAWN_EGG
  - SKELETON_SPAWN_EGG
  - SKELETON_HORSE_SPAWN_EGG
  - SLIME_SPAWN_EGG
  - SNIFFER_SPAWN_EGG
  - SNOW_GOLEM_SPAWN_EGG
  - SPIDER_SPAWN_EGG
  - SQUID_SPAWN_EGG
  - STRAY_SPAWN_EGG
  - STRIDER_SPAWN_EGG
  - TADPOLE_SPAWN_EGG
  - TRADER_LLAMA_SPAWN_EGG
  - TROPICAL_FISH_SPAWN_EGG
  - TURTLE_SPAWN_EGG
  - VEX_SPAWN_EGG
  - VILLAGER_SPAWN_EGG
  - VINDICATOR_SPAWN_EGG
  - WANDERING_TRADER_SPAWN_EGG
  - WARDEN_SPAWN_EGG
  - WITCH_SPAWN_EGG
  - WITHER_SPAWN_EGG
  - WITHER_SKELETON_SPAWN_EGG
  - WOLF_SPAWN_EGG
  - ZOGLIN_SPAWN_EGG
  - ZOMBIE_SPAWN_EGG
  - ZOMBIE_HORSE_SPAWN_EGG
  - ZOMBIE_VILLAGER_SPAWN_EGG
  - ZOMBIFIED_PIGLIN_SPAWN_EGG
  - BOGGED_SPAWN_EGG
  - BREEZE_SPAWN_EGG
  - TRIAL_SPAWNER
  - VAULT
  - PLAYER_HEAD
  - COMMAND_BLOCK_MINECART
  - KNOWLEDGE_BOOK
  - DEBUG_STICK
  - SUSPICIOUS_GRAVEL
  - SUSPICIOUS_SAND
disabled-entities:
  - AREA_EFFECT_CLOUD
  - ARROW
  - BLOCK_DISPLAY
  - DRAGON_FIREBALL
  - EGG
  - END_CRYSTAL
  - ENDER_PEARL
  - EYE_OF_ENDER
  - EVOKER_FANGS
  - EXPERIENCE_ORB
  - FALLING_BLOCK
  - FIREBALL
  - FIREWORK_ROCKET
  - FISHING_BOBBER
  - GIANT
  - GLOW_ITEM_FRAME
  - ILLUSIONER
  - INTERACTION
  - ITEM
  - ITEM_DISPLAY
  - ITEM_FRAME
  - LEASH_KNOT
  - LLAMA_SPIT
  - LIGHTNING_BOLT
  - MARKER
  - MINECART
  - CHEST_MINECART
  - COMMAND_BLOCK_MINECART
  - FURNACE_MINECART
  - HOPPER_MINECART
  - SPAWNER_MINECART
  - TNT_MINECART
  - PAINTING
  - PLAYER
  - TNT
  - SHULKER_BULLET
  - SMALL_FIREBALL
  - SNOWBALL
  - SPECTRAL_ARROW
  - SPLASH_POTION
  - TEXT_DISPLAY
  - EXPERIENCE_BOTTLE
  - UNKNOWN
  - ZOMBIE_HORSE
  - WITHER_SKULL
  - TRIDENT
  - ARMOR_STAND
  - ACACIA_BOAT
  - ACACIA_CHEST_BOAT
  - BAMBOO_RAFT
  - BAMBOO_CHEST_RAFT
  - BIRCH_BOAT
  - BIRCH_CHEST_BOAT
  - CHERRY_BOAT
  - CHERRY_CHEST_BOAT
  - DARK_OAK_BOAT
  - DARK_OAK_CHEST_BOAT
  - JUNGLE_BOAT
  - JUNGLE_CHEST_BOAT
  - MANGROVE_BOAT
  - MANGROVE_CHEST_BOAT
  - OAK_BOAT
  - OAK_CHEST_BOAT
  - PALE_OAK_BOAT
  - PALE_OAK_CHEST_BOAT
  - SPRUCE_BOAT
  - SPRUCE_CHEST_BOAT
  - BREEZE_WIND_CHARGE
disabled-biomes:
  - THE_VOID
  - CUSTOM
persistent-data:
  timer: